### ISSUE TITLE
Similar to Jitsi Videobridge?

### ISSUE THREAD

**Issue by poVoq** [Johni0702/mumble-web-proxy#5]
Does this make a Mumble server act similar to the Jisti videobridge* by mixing and relaying multiple WebRTC streams?

* https://jitsi.org/jitsi-videobridge/

**Comment by Johni0702** [comment]
I'm not too familiar with the internal workings of the jitsi videobridge but if I'm not entirely mistaken, then yes, this will behave somewhat similar to the jitsi videobridge, except:
- It doesn't do any relaying to other clients, it only relays incoming voice packets on WebRTC to the backing Mumble server and the other way around. The Mumble server is responsible for relaying between different clients.
- It doesn't do any mixing, each connected user gets `1+n` WebRTC streams (`1` for their mic, and one for every other of the `n` users connected to the backing Mumble server). Though I believe Jitsi doesn't do any mixing either.
- It is a rather dumb proxy, i.e. it doesn't do any of the usual connection quality / bandwidth reporting which normal WebRTC endpoints do. This would be really bad for video where people's bandwidth may very well be smaller than the video stream (which is why jitsi has to do it) but it isn't really an issue for this bridge as it's voice-only and voice usually requires far less bandwidth than is available (and since native Mumble clients don't support it, the bridge cannot support it anyway).
- It also does websocket termination i.e. the code running in the browser can talk to the backing Mumble server using the native Mumble protocol and this proxy just wraps that stream into the websocket protocol which browsers can natively understand
